// flow-typed signature: 04cccabcca5c18d1b79f76df9c06ed49
// flow-typed version: <<STUB>>/@octokit/rest_v16.7/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@octokit/rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@octokit/rest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@octokit/rest/lib/constructor' {
  declare module.exports: any;
}

declare module '@octokit/rest/lib/core' {
  declare module.exports: any;
}

declare module '@octokit/rest/lib/factory' {
  declare module.exports: any;
}

declare module '@octokit/rest/lib/parse-client-options' {
  declare module.exports: any;
}

declare module '@octokit/rest/lib/register-plugin' {
  declare module.exports: any;
}

declare module '@octokit/rest/lib/request-with-defaults' {
  declare module.exports: any;
}

declare module '@octokit/rest/plugins/authentication/authenticate' {
  declare module.exports: any;
}

declare module '@octokit/rest/plugins/authentication/before-request' {
  declare module.exports: any;
}

declare module '@octokit/rest/plugins/authentication/index' {
  declare module.exports: any;
}

declare module '@octokit/rest/plugins/pagination/index' {
  declare module.exports: any;
}

declare module '@octokit/rest/plugins/pagination/iterator' {
  declare module.exports: any;
}

declare module '@octokit/rest/plugins/pagination/paginate' {
  declare module.exports: any;
}

declare module '@octokit/rest/plugins/register-endpoints/index' {
  declare module.exports: any;
}

declare module '@octokit/rest/plugins/register-endpoints/register-endpoints' {
  declare module.exports: any;
}

declare module '@octokit/rest/plugins/rest-api-endpoints/index' {
  declare module.exports: any;
}

declare module '@octokit/rest/plugins/validate/index' {
  declare module.exports: any;
}

declare module '@octokit/rest/plugins/validate/validate' {
  declare module.exports: any;
}

// Filename aliases
declare module '@octokit/rest/index' {
  declare module.exports: $Exports<'@octokit/rest'>;
}
declare module '@octokit/rest/index.js' {
  declare module.exports: $Exports<'@octokit/rest'>;
}
declare module '@octokit/rest/lib/constructor.js' {
  declare module.exports: $Exports<'@octokit/rest/lib/constructor'>;
}
declare module '@octokit/rest/lib/core.js' {
  declare module.exports: $Exports<'@octokit/rest/lib/core'>;
}
declare module '@octokit/rest/lib/factory.js' {
  declare module.exports: $Exports<'@octokit/rest/lib/factory'>;
}
declare module '@octokit/rest/lib/parse-client-options.js' {
  declare module.exports: $Exports<'@octokit/rest/lib/parse-client-options'>;
}
declare module '@octokit/rest/lib/register-plugin.js' {
  declare module.exports: $Exports<'@octokit/rest/lib/register-plugin'>;
}
declare module '@octokit/rest/lib/request-with-defaults.js' {
  declare module.exports: $Exports<'@octokit/rest/lib/request-with-defaults'>;
}
declare module '@octokit/rest/plugins/authentication/authenticate.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/authentication/authenticate'>;
}
declare module '@octokit/rest/plugins/authentication/before-request.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/authentication/before-request'>;
}
declare module '@octokit/rest/plugins/authentication/index.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/authentication/index'>;
}
declare module '@octokit/rest/plugins/pagination/index.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/pagination/index'>;
}
declare module '@octokit/rest/plugins/pagination/iterator.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/pagination/iterator'>;
}
declare module '@octokit/rest/plugins/pagination/paginate.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/pagination/paginate'>;
}
declare module '@octokit/rest/plugins/register-endpoints/index.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/register-endpoints/index'>;
}
declare module '@octokit/rest/plugins/register-endpoints/register-endpoints.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/register-endpoints/register-endpoints'>;
}
declare module '@octokit/rest/plugins/rest-api-endpoints/index.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/rest-api-endpoints/index'>;
}
declare module '@octokit/rest/plugins/validate/index.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/validate/index'>;
}
declare module '@octokit/rest/plugins/validate/validate.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/validate/validate'>;
}
